feat: [part-encrypt] Add separation header part encrypt logic code
linuxdeepin/dde-file-manager-extensions pull request #99
Opened 2024-03-15 07:01 UTC by GongHeng2017

Add separation header part encrypt logic code

Log: add feature of separation header part encrypt. Task:

2024-03-15 07:14 UTC, itsXuSt requested changes

2024-03-15 07:14 UTC, itsXuSt commented on src/dde-file-manager-daemon/daemonplugin-file-encrypt/dbus/diskencryptdbus.cpp
> +static constexpr char kBootUsecPath[] { "/boot/usec-crypt" };
globaltypedefines.h 中有相关定义。

2024-03-15 07:14 UTC, itsXuSt commented on src/dde-file-manager-daemon/daemonplugin-file-encrypt/dbus/diskencryptdbus.cpp
> +        QJsonObject obj;
有现成的函数，为什么要自己写这么大一坨？

2024-03-15 07:14 UTC, itsXuSt commented on src/dde-file-manager-daemon/daemonplugin-file-encrypt/dbus/diskencryptdbus.cpp
> +bool DiskEncryptDBus::HasConfigFile(const QString &filePath)
EncryptStatus 返回的 flags 中新增一个 kNoEncryptConfig 枚举，在 EncryptStatus 函数中去检查文件是否存在。以 flags 方式返回。

2024-03-15 07:14 UTC, itsXuSt commented on src/dde-file-manager/dfmplugin-disk-encrypt-entry/menu/diskencryptmenuscene.cpp
> +static constexpr char kBootUsecPath[] { "/boot/usec-crypt" };
没地方使用，定义来干嘛的？

2024-03-15 07:14 UTC, itsXuSt commented on src/dde-file-manager/dfmplugin-disk-encrypt-entry/menu/diskencryptmenuscene.cpp
> +//    auto preferDev = selectedItemInfo.value("PreferredDevice", "").toString();
这段代码为了解决一个2级问题，加入后将导致2级问题被激活。
https://pms.uniontech.com/bug-view-232171.html

2024-03-15 07:14 UTC, itsXuSt commented on src/dde-file-manager/dfmplugin-disk-encrypt-entry/menu/diskencryptmenuscene.cpp
> +        int states = EventsHandler::instance()->deviceEncryptStatus(device);
在 update 函数中去做处理。initialize 函数不要判定这些东西。

2024-03-15 07:14 UTC, itsXuSt commented on src/dde-file-manager/dfmplugin-disk-encrypt-entry/menu/diskencryptmenuscene.cpp
> +        bool hasConfig { EventsHandler::instance()->hasConfigFile(filePath) };
你通过传入文件路径到 daemon DBus 接口来判定一个文件是否存在，太危险了。

2024-03-15 07:14 UTC, itsXuSt commented on src/dde-file-manager/dfmplugin-disk-encrypt-entry/menu/diskencryptmenuscene.cpp
> +        bool hasConfig { EventsHandler::instance()->hasConfigFile(filePath) };
我可以传入任意的文件路径

2024-03-15 07:14 UTC, itsXuSt commented on src/dde-file-manager-daemon/daemonplugin-file-encrypt/dbus/diskencryptdbus.cpp
> +        triggerReencrypt(device);
在 preencrypt 里调用 reencrypt 是绝对错误的写法。

2024-03-15 07:18 UTC, itsXuSt requested changes

2024-03-15 07:18 UTC, itsXuSt commented on src/dde-file-manager-daemon/daemonplugin-file-encrypt/dbus/diskencryptdbus.cpp
> +    if (params.value(encrypt_param_keys::kKeySeparationHeaderPartEncrypt).toBool()) {
PreencryptWorker 就是做写配置的事情的，为什么要在调用 worker 的地方再写一堆？可以复用逻辑。

2024-03-15 08:52 UTC, itsXuSt requested changes

2024-03-15 08:52 UTC, itsXuSt commented on src/dde-file-manager-daemon/daemonplugin-file-encrypt/encrypt/encryptworker.cpp
> +    if (!params.value(encrypt_param_keys::kKeySeparationHeaderPartEncrypt).toBool()) {
if(param......) { 
writexxxxxx()
return;
}

把你的判断完，后边的缩进不要动。

2024-03-15 08:52 UTC, itsXuSt commented on src/dde-file-manager-daemon/daemonplugin-file-encrypt/encrypt/diskencrypt.cpp
> +    QFile f(configFile);
尽在加密未完成的时候才需要考虑增加这个 flag

2024-03-18 07:53 UTC, itsXuSt approved these changes

2024-03-18 07:54 UTC, GongHeng2017 commented on src/dde-file-manager-daemon/daemonplugin-file-encrypt/dbus/diskencryptdbus.cpp
> +static constexpr char kBootUsecPath[] { "/boot/usec-crypt" };
done

2024-03-18 07:54 UTC, GongHeng2017 commented on src/dde-file-manager-daemon/daemonplugin-file-encrypt/dbus/diskencryptdbus.cpp
> +        QJsonObject obj;
done

2024-03-18 07:54 UTC, GongHeng2017 commented on src/dde-file-manager-daemon/daemonplugin-file-encrypt/dbus/diskencryptdbus.cpp
> +static constexpr char kBootUsecPath[] { "/boot/usec-crypt" };
done

2024-03-18 07:54 UTC, GongHeng2017 commented on src/dde-file-manager-daemon/daemonplugin-file-encrypt/dbus/diskencryptdbus.cpp
> +static constexpr char kBootUsecPath[] { "/boot/usec-crypt" };
done

2024-03-18 07:54 UTC, GongHeng2017 commented on src/dde-file-manager-daemon/daemonplugin-file-encrypt/dbus/diskencryptdbus.cpp
> +bool DiskEncryptDBus::HasConfigFile(const QString &filePath)
done

2024-03-18 07:55 UTC, GongHeng2017 commented on src/dde-file-manager/dfmplugin-disk-encrypt-entry/menu/diskencryptmenuscene.cpp
> +//    auto preferDev = selectedItemInfo.value("PreferredDevice", "").toString();
done

2024-03-18 07:55 UTC, GongHeng2017 commented on src/dde-file-manager/dfmplugin-disk-encrypt-entry/menu/diskencryptmenuscene.cpp
> +        int states = EventsHandler::instance()->deviceEncryptStatus(device);
done

2024-03-18 07:55 UTC, GongHeng2017 commented on src/dde-file-manager/dfmplugin-disk-encrypt-entry/menu/diskencryptmenuscene.cpp
> +        bool hasConfig { EventsHandler::instance()->hasConfigFile(filePath) };
done

2024-03-18 07:55 UTC, GongHeng2017 commented on src/dde-file-manager-daemon/daemonplugin-file-encrypt/dbus/diskencryptdbus.cpp
> +    if (params.value(encrypt_param_keys::kKeySeparationHeaderPartEncrypt).toBool()) {
done

2024-03-18 07:55 UTC, GongHeng2017 commented on src/dde-file-manager-daemon/daemonplugin-file-encrypt/encrypt/encryptworker.cpp
> +    if (!params.value(encrypt_param_keys::kKeySeparationHeaderPartEncrypt).toBool()) {
done

2024-03-18 07:55 UTC, GongHeng2017 commented on src/dde-file-manager-daemon/daemonplugin-file-encrypt/encrypt/diskencrypt.cpp
> +    QFile f(configFile);
done

2024-03-18 07:55 UTC, GongHeng2017 commented
/merge

2024-03-18 07:56 UTC, merged